/*
 *TEXTOS DE ALARMAS
*/

// #define ALARM0 "EMERGENCY STOP"
// #define ALARM1 "LOW OIL PRESSURE"
// #define ALARM2 "HIGH COOLANT TEMPERATURE"
// #define ALARM3 "LOW COOLANT TEMPERATURE"
// #define ALARM4 "UNDER SPEED"
// #define ALARM5 "OVER SPEED"
// #define ALARM6 "GENERATOR UNDER FREQUENCY"
// #define ALARM7 "GENERATOR OVER FREQUENCY"
// #define ALARM8 "GENERATOR LOW VOLTAGE"
// #define ALARM9 "GENERATOR HIGH VOLTAGE"
// #define ALARM10 "BATTERY LOW VOLTAGE"
// #define ALARM11 "BATTERY HIGH VOLTAGE"
// #define ALARM12 "CHARGE ALTERNATOR FAILURE"
// #define ALARM13 "FAIL TO START"
// #define ALARM14 "FAIL TO STOP"
// #define ALARM15 "GENERATOR FAIL TO CLOSE"
// #define ALARM16 "MAINS FAIL TO CLOSE"
// #define ALARM17 "OIL PRESSURE SENDER FAULT"
// #define ALARM18 "LOSS OF MAGNETIC PICK UP"
// #define ALARM19 "MAG PICKUP OPEN CIRCUIT"
// #define ALARM20 "GENERATOR HIGH CURRENT"
// #define ALARM21 "CALIBRATION LOST"
// #define ALARM22 "LOW FUEL LEVEL"
// #define ALARM23 "CAN ECU WARNING"
// #define ALARM24 "CAN ECU SHUTDOWN"
// #define ALARM25 "CAN ECU DATA FAIL"
// #define ALARM26 "LOW OIL LEVEL SWITCH"
// #define ALARM27 "HIGH TEMPERATURE SWITCH"
// #define ALARM28 "LOW FUEL LEVEL SWITCH"
// #define ALARM29 "EXPANSION UNIT WATCHDOG "
// #define ALARM30 "KW OVERLOAD"
// #define ALARM31 "NEGATIVE PHASE SEQ CURRENT"
// #define ALARM32 "EARTH FAULT TRIP"
// #define ALARM33 "GENERATOR PHASE ROTATION"
// #define ALARM34 "AUTO VOLTAGE SENSE FAIL"
// #define ALARM35 "MAINTENANCE"
// #define ALARM36 "LOADING FREQUENCY"
// #define ALARM37 "LOADING VOLTAGE"
// #define ALARM38 "FUEL USAGE RUNNING"
// #define ALARM39 "FUEL USAGE STOPPED"
// #define ALARM40 "PROTECTIONS DISABLED"
// #define ALARM41 "PROTECTIONS BLOCKED"
// #define ALARM42 "GEN BREAKER FAILED TO OPEN"
// #define ALARM43 "MAINS BKR FAILED TO OPEN"
// #define ALARM44 "BUS BREAKER FAILED TO CLOSE"
// #define ALARM45 "BUS BREAKER FAILED TO OPEN"
// #define ALARM46 "GENERATOR REV POWER "
// #define ALARM47 "SHORT CIRCUIT"
// #define ALARM48 "AIR FLAP CLOSED"
// #define ALARM49 "FAILURE TO SYNC"
// #define ALARM50 "BUS LIVE"
// #define ALARM51 "BUS NOT LIVE"
// #define ALARM52 "BUS PHASE ROTATION"
// #define ALARM53 "PRIORITY SELECTION ERROR"
// #define ALARM54 "MSC DATA ERROR"
// #define ALARM55 "MSC ID ERROR"
// #define ALARM56 "BUS LOW VOLTAGE"
// #define ALARM57 "BUS HIGH VOLTAGE"
// #define ALARM58 "BUS LOW FREQUENCY"
// #define ALARM59 "BUS HIGH FREQUENCY"
// #define ALARM60 "MSC FAILURE"
// #define ALARM61 "MSC TOO FEW SETS"
// #define ALARM62 "MSC S INHIBITED"
// #define ALARM63 "MSC OLD VER UNITS ON THE BUS"
// #define ALARM64 "MAINS REV PWR/MAINS EXP"
// #define ALARM65 "MINIMUM SETS NOT REACHED"
// #define ALARM66 "INSUFFICIENT CAPACITY"
// #define ALARM67 "OUT OF SYNC"
// #define ALARM68 "ALTERNATIVE AUX MAINS FAIL"
// #define ALARM69 "LOSS OF EXCITATION"
// #define ALARM70 "MAINS ROCOF"
// #define ALARM71 "MAINS VECTOR SHIFT"
// #define ALARM72 "MAINS DEC LOW FREQUENCY"
// #define ALARM73 "MAINS DEC HIGH FREQUENCY"
// #define ALARM74 "MAINS DEC LOW VOLTAGE"
// #define ALARM75 "MAINS DEC HIGH VOLTAGE"
// #define ALARM76 "MAINS DEC COMBINED "
// #define ALARM77 "INLET TEMPERATURE"
// #define ALARM78 "MAINS PHASE ROT  IDENTIFIER"
// #define ALARM79 "AVR MAX TRIM LIMIT"
// #define ALARM80 "HIGH COOLANT TEMP ELEC TRIP "
// #define ALARM81 "TEMP SENDER OPEN CIRCUIT"
// #define ALARM82 "OUT OF SYNC BUS"
// #define ALARM83 "OUT OF SYNC MAINS"
// #define ALARM84 "BUS 1 LIVE"
// #define ALARM85 "BUS 1 PHASE ROTATION"
// #define ALARM86 "BUS 2 LIVE"
// #define ALARM87 "BUS 2 PHASE ROTATION"
// #define ALARM88 "UNIMPLEMENTED"
// #define ALARM89 "ECU PROTECT"
// #define ALARM90 "ECU MALFUNCTION"
// #define ALARM91 "INDICATION"
// #define ALARM92 "UNIMPLEMENTED"
// #define ALARM93 "UNIMPLEMENTED"
// #define ALARM94 "HEST ACTIVE"
// #define ALARM95 "DPTC FILTER"
// #define ALARM96 "WATER IN FUEL"
// #define ALARM97 "ECU HEATER"
// #define ALARM98 "ECU COOLER"
// #define ALARM99 "UNIMPLEMENTED"
// #define ALARM100 "UNIMPLEMENTED"
// #define ALARM101 "UNIMPLEMENTED"
// #define ALARM102 "UNIMPLEMENTED"
// #define ALARM103 "UNIMPLEMENTED"
// #define ALARM104 "UNIMPLEMENTED"
// #define ALARM105 "UNIMPLEMENTED"
// #define ALARM106 "UNIMPLEMENTED"
// #define ALARM107 "UNIMPLEMENTED"
// #define ALARM108 "HIGH FUEL LEVEL"
// #define ALARM109 "UNIMPLEMENTED"
// #define ALARM110 "MODULE COMMUNICATION FAIL"
// #define ALARM111 "BUS MODULE WARNING"
// #define ALARM112 "BUS MODULE TRIP"
// #define ALARM113 "MAINS MODULE WARNING"
// #define ALARM114 "MAINS MODULE TRIP"
// #define ALARM115 "LOAD LIVE"
// #define ALARM116 "LOAD NOT LIVE"
// #define ALARM117 "LOAD PHASE ROTATION"
// #define ALARM118 "DEF LEVEL LOW"
// #define ALARM119 "SCR INDUCEMENT"
// #define ALARM120 "HEATER SENSOR FAILURE"
// #define ALARM121 "MAINS OVER ZERO SEQ VOLTS"
// #define ALARM122 "MAINS UNDER POS SEQ VOLTS"
// #define ALARM123 "MAINS OVER NEG SEQ VOLTS"
// #define ALARM124 "MAINS ASYMMETRY HIGH"
// #define ALARM125 "BUS OVER ZERO SEQ VOLTS"
// #define ALARM126 "BUS UNDER POSITIVE SEQ VOLTS"
// #define ALARM127 "BUS OVER NEGATIVE SEQ VOLTS"
// #define ALARM128 "BUS ASYMMETRY HIGH"
// #define ALARM129 "E-TRIP STOP INHIBITED"
// #define ALARM130 "FUEL TANK BUND LEVEL HIGH"
// #define ALARM131 "MSC LINK 1 DATA ERROR"
// #define ALARM132 "MSC LINK 2 DATA ERROR"
// #define ALARM133 "BUS 2 LOW VOLTAGE"
// #define ALARM134 "BUS 2 HIGH VOLTAGE"
// #define ALARM135 "BUS 2 LOW FREQUENCY"
// #define ALARM136 "BUS 2 HIGH FREQUENCY"
// #define ALARM137 "MSC LINK 1 FAILURE"
// #define ALARM138 "MSC LINK 2 FAILURE"
// #define ALARM139 "MSC LINK 1 TOO FEW SETS"
// #define ALARM140 "MSC LINK 2 TOO FEW SETS"
// #define ALARM141 "MSC LINK 1 AND 2 FAILURE"
// #define ALARM142 "ELECTRICAL TRIP FROM 8660"
// #define ALARM143 "AVR CAN RED STOP LAMP FAULT"
// #define ALARM144 "GEN OVER ZERO SEQ VOLTS"
// #define ALARM145 "GEN UNDER POS SEQ VOLTS"
// #define ALARM146 "GEN OVER NEG SEQ VOLTS"
// #define ALARM147 "GEN ASYMMETRY HIGH"
String DSEAlarmsString[148];

void asignAlarm(){
  DSEAlarmsString[0] = F("EMERGENCY STOP");
  DSEAlarmsString[1] = F("LOW OIL PRESSURE");
  DSEAlarmsString[2] = F("HIGH COOLANT TEMPERATURE");
  DSEAlarmsString[3] = F("LOW COOLANT TEMPERATURE");

  DSEAlarmsString[4] = F("UNDER SPEED");
  DSEAlarmsString[5] = F("OVER SPEED");
  DSEAlarmsString[6] = F("GENERATOR UNDER FREQUENCY");
  DSEAlarmsString[7] = F("GENERATOR OVER FREQUENCY");

  DSEAlarmsString[8] = F("GENERATOR LOW VOLTAGE");
  DSEAlarmsString[9] = F("GENERATOR HIGH VOLTAGE");
  DSEAlarmsString[10] = F("BATTERY LOW VOLTAGE");
  DSEAlarmsString[11] = F("BATTERY HIGH VOLTAGE");

  DSEAlarmsString[12] = F("CHARGE ALTERNATOR FAILURE");
  DSEAlarmsString[13] = F("FAIL TO START");
  DSEAlarmsString[14] = F("FAIL TO STOP");
  DSEAlarmsString[15] = F("GENERATOR FAIL TO CLOSE");

  DSEAlarmsString[16] = F("MAINS FAIL TO CLOSE");
  DSEAlarmsString[17] = F("OIL PRESSURE SENDER FAULT");
  DSEAlarmsString[18] = F("LOSS OF MAGNETIC PICK UP");
  DSEAlarmsString[19] = F("MAG PICKUP OPEN CIRCUIT");

  DSEAlarmsString[20] = F("GENERATOR HIGH CURRENT");
  DSEAlarmsString[21] = F("CALIBRATION LOST");
  DSEAlarmsString[22] = F("LOW FUEL LEVEL");
  DSEAlarmsString[23] = F("CAN ECU WARNING");

  DSEAlarmsString[24] = F("CAN ECU SHUTDOWN");
  DSEAlarmsString[25] = F("CAN ECU DATA FAIL");
  DSEAlarmsString[26] = F("LOW OIL LEVEL SWITCH");
  DSEAlarmsString[27] = F("HIGH TEMPERATURE SWITCH");

  DSEAlarmsString[28] = F("LOW FUEL LEVEL SWITCH");
  DSEAlarmsString[29] = F("EXPANSION UNIT WATCHDOG ");
  DSEAlarmsString[30] = F("KW OVERLOAD");
  DSEAlarmsString[31] = F("NEGATIVE PHASE SEQ CURRENT");

  DSEAlarmsString[32] = F("EARTH FAULT TRIP");
  DSEAlarmsString[33] = F("GENERATOR PHASE ROTATION");
  DSEAlarmsString[34] = F("AUTO VOLTAGE SENSE FAIL");
  DSEAlarmsString[35] = F("MAINTENANCE");

  DSEAlarmsString[36] = F("LOADING FREQUENCY");
  DSEAlarmsString[37] = F("LOADING VOLTAGE");
  DSEAlarmsString[38] = F("FUEL USAGE RUNNING");
  DSEAlarmsString[39] = F("FUEL USAGE STOPPED");

  DSEAlarmsString[40] = F("PROTECTIONS DISABLED");
  DSEAlarmsString[41] = F("PROTECTIONS BLOCKED");
  DSEAlarmsString[42] = F("GEN BREAKER FAILED TO OPEN");
  DSEAlarmsString[43] = F("MAINS BKR FAILED TO OPEN");

  DSEAlarmsString[44] = F("BUS BREAKER FAILED TO CLOSE");
  DSEAlarmsString[45] = F("BUS BREAKER FAILED TO OPEN");
  DSEAlarmsString[46] = F("GENERATOR REV POWER ");
  DSEAlarmsString[47] = F("SHORT CIRCUIT");

  DSEAlarmsString[48] = F("AIR FLAP CLOSED");
  DSEAlarmsString[49] = F("FAILURE TO SYNC");
  DSEAlarmsString[50] = F("BUS LIVE");
  DSEAlarmsString[51] = F("BUS NOT LIVE");

  DSEAlarmsString[52] = F("BUS PHASE ROTATION");
  DSEAlarmsString[53] = F("PRIORITY SELECTION ERROR");
  DSEAlarmsString[54] = F("MSC DATA ERROR");
  DSEAlarmsString[55] = F("MSC ID ERROR");

  DSEAlarmsString[56] = F("BUS LOW VOLTAGE");
  DSEAlarmsString[57] = F("BUS HIGH VOLTAGE");
  DSEAlarmsString[58] = F("BUS LOW FREQUENCY");
  DSEAlarmsString[59] = F("BUS HIGH FREQUENCY");

  DSEAlarmsString[60] = F("MSC FAILURE");
  DSEAlarmsString[61] = F("MSC TOO FEW SETS");
  DSEAlarmsString[62] = F("MSC S INHIBITED");
  DSEAlarmsString[63] = F("MSC OLD VER UNITS ON THE BUS");

  DSEAlarmsString[64] = F("MAINS REV PWR/MAINS EXP");
  DSEAlarmsString[65] = F("MINIMUM SETS NOT REACHED");
  DSEAlarmsString[66] = F("INSUFFICIENT CAPACITY");
  DSEAlarmsString[67] = F("OUT OF SYNC");

  DSEAlarmsString[68] = F("ALTERNATIVE AUX MAINS FAIL");
  DSEAlarmsString[69] = F("LOSS OF EXCITATION");
  DSEAlarmsString[70] = F("MAINS ROCOF");
  DSEAlarmsString[71] = F("MAINS VECTOR SHIFT");

  DSEAlarmsString[72] = F("MAINS DEC LOW FREQUENCY");
  DSEAlarmsString[73] = F("MAINS DEC HIGH FREQUENCY");
  DSEAlarmsString[74] = F("MAINS DEC LOW VOLTAGE");
  DSEAlarmsString[75] = F("MAINS DEC HIGH VOLTAGE");

  DSEAlarmsString[76] = F("MAINS DEC COMBINED ");
  DSEAlarmsString[77] = F("INLET TEMPERATURE");
  DSEAlarmsString[78] = F("MAINS PHASE ROT  IDENTIFIER");
  DSEAlarmsString[79] = F("AVR MAX TRIM LIMIT");

  DSEAlarmsString[80] = F("HIGH COOLANT TEMP ELEC TRIP ");
  DSEAlarmsString[81] = F("TEMP SENDER OPEN CIRCUIT");
  DSEAlarmsString[82] = F("OUT OF SYNC BUS");
  DSEAlarmsString[83] = F("OUT OF SYNC MAINS");

  DSEAlarmsString[84] = F("BUS 1 LIVE");
  DSEAlarmsString[85] = F("BUS 1 PHASE ROTATION");
  DSEAlarmsString[86] = F("BUS 2 LIVE");
  DSEAlarmsString[87] = F("BUS 2 PHASE ROTATION");

  DSEAlarmsString[88] = F("UNIMPLEMENTED");
  DSEAlarmsString[89] = F("ECU PROTECT");
  DSEAlarmsString[90] = F("ECU MALFUNCTION");
  DSEAlarmsString[91] = F("INDICATION");

  DSEAlarmsString[92] = F("UNIMPLEMENTED");
  DSEAlarmsString[93] = F("UNIMPLEMENTED");
  DSEAlarmsString[94] = F("HEST ACTIVE");
  DSEAlarmsString[95] = F("DPTC FILTER");

  DSEAlarmsString[96] = F("WATER IN FUEL");
  DSEAlarmsString[97] = F("ECU HEATER");
  DSEAlarmsString[98] = F("ECU COOLER");
  DSEAlarmsString[99] = F("UNIMPLEMENTED");

  DSEAlarmsString[100] = F("UNIMPLEMENTED");
  DSEAlarmsString[101] = F("UNIMPLEMENTED");
  DSEAlarmsString[102] = F("UNIMPLEMENTED");
  DSEAlarmsString[103] = F("UNIMPLEMENTED");

  DSEAlarmsString[104] = F("UNIMPLEMENTED");
  DSEAlarmsString[105] = F("UNIMPLEMENTED");
  DSEAlarmsString[106] = F("UNIMPLEMENTED");
  DSEAlarmsString[107] = F("UNIMPLEMENTED");

  DSEAlarmsString[108] = F("HIGH FUEL LEVEL");
  DSEAlarmsString[109] = F("UNIMPLEMENTED");
  DSEAlarmsString[110] = F("MODULE COMMUNICATION FAIL");
  DSEAlarmsString[111] = F("BUS MODULE WARNING");

  DSEAlarmsString[112] = F("BUS MODULE TRIP");
  DSEAlarmsString[113] = F("MAINS MODULE WARNING");
  DSEAlarmsString[114] = F("MAINS MODULE TRIP");
  DSEAlarmsString[115] = F("LOAD LIVE");

  DSEAlarmsString[116] = F("LOAD NOT LIVE");
  DSEAlarmsString[117] = F("LOAD PHASE ROTATION");
  DSEAlarmsString[118] = F("DEF LEVEL LOW");
  DSEAlarmsString[119] = F("SCR INDUCEMENT");

  DSEAlarmsString[120] = F("HEATER SENSOR FAILURE");
  DSEAlarmsString[121] = F("MAINS OVER ZERO SEQ VOLTS");
  DSEAlarmsString[122] = F("MAINS UNDER POS SEQ VOLTS");
  DSEAlarmsString[123] = F("MAINS OVER NEG SEQ VOLTS");

  DSEAlarmsString[124] = F("MAINS ASYMMETRY HIGH");
  DSEAlarmsString[125] = F("BUS OVER ZERO SEQ VOLTS");
  DSEAlarmsString[126] = F("BUS UNDER POSITIVE SEQ VOLTS");
  DSEAlarmsString[127] = F("BUS OVER NEGATIVE SEQ VOLTS");

  DSEAlarmsString[128] = F("BUS ASYMMETRY HIGH");
  DSEAlarmsString[129] = F("E-TRIP STOP INHIBITED");
  DSEAlarmsString[130] = F("FUEL TANK BUND LEVEL HIGH");
  DSEAlarmsString[131] = F("MSC LINK 1 DATA ERROR");

  DSEAlarmsString[132] = F("MSC LINK 2 DATA ERROR");
  DSEAlarmsString[133] = F("BUS 2 LOW VOLTAGE");
  DSEAlarmsString[134] = F("BUS 2 HIGH VOLTAGE");
  DSEAlarmsString[135] = F("BUS 2 LOW FREQUENCY");

  DSEAlarmsString[136] = F("BUS 2 HIGH FREQUENCY");
  DSEAlarmsString[137] = F("MSC LINK 1 FAILURE");
  DSEAlarmsString[138] = F("MSC LINK 2 FAILURE");
  DSEAlarmsString[139] = F("MSC LINK 1 TOO FEW SETS");

  DSEAlarmsString[140] = F("MSC LINK 2 TOO FEW SETS");
  DSEAlarmsString[141] = F("MSC LINK 1 AND 2 FAILURE");
  DSEAlarmsString[142] = F("ELECTRICAL TRIP FROM 8660");
  DSEAlarmsString[143] = F("AVR CAN RED STOP LAMP FAULT");
  
  DSEAlarmsString[144] = F("GEN OVER ZERO SEQ VOLTS");
  DSEAlarmsString[145] = F("GEN UNDER POS SEQ VOLTS");
  DSEAlarmsString[146] = F("GEN OVER NEG SEQ VOLTS");
  DSEAlarmsString[147] = F("GEN ASYMMETRY HIGH");
}
